### ISSUE TITLE
Compatibility with rdflib version

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/sphinx_probs_rdf#4]
It seems changes in rdflib after 6.1.1 removed the `preferredLabel` method -- we should specify a maximum version here in setup.cfg

**Comment by stephenjboyle** [comment]
@ricklupton 
Hi Rick, I've made a new branch with changes to ```setup.cfg``` and ```directives.py``` (for changes to probs prefix). Can you give me access to push to repository. Thanks

**Comment by ricklupton** [comment]
Hi @stephenjboyle thanks for doing this. Unfortunately as per https://github.com/probs-lab/petrochemical-integrated-data/issues/39 I think we might need to fix it and allow versions >= 6.2, <7.

Can you just copy the definition of preferredLabel from here:

https://github.com/RDFLib/rdflib/blob/2fc55b38c40a0f7df6b44989cd52a6b3ce5d1540/rdflib/graph.py#L722-L799

into the file here in this repository, just above where it is used? 

And update setup.cfg to specify at least 6.2, less than 7 (to avoid any other possible breaking changes that came in there).

This is a bit of an unusual case, it looks like these methods were supposed to be removed for the major version 6.0, but were missed, which is why they went ahead and removed them for a minor version. Normally we *should* be "safe" specifying a dependency as a particular major version.

Thanks,
Rick

**Comment by ricklupton** [comment]
@stephenjboyle I've invited you to this repository

**Comment by ricklupton** [comment]
Closed by #5
